// largely generated by claude with review

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { listConnections,
       callTools,
       inject,
} from './wsConnect.js'
import { getEntries, getInstructions, } from './entries.js';

const fns = { listConnections, callTools, inject, };
const entries = getEntries(fns);

// transport-agnostic: no transport is imported or connected here
export const createServer = (sessionToken) => {
    const server = new McpServer({
        name: '46a-mcp-server',
        version: '1.0.0'
    }, { instructions: getInstructions() })

    const boundFns = {
        listConnections: (opts) => listConnections(opts, sessionToken),
        callTools: (toolCalls) => callTools(toolCalls, sessionToken),
        inject: (injectCall) => inject(injectCall, sessionToken),
    }
    getEntries(boundFns).forEach(entry => server.registerTool(...entry))

    return server
}

export const testEntryPoint = async (inputName, args) => {
    for(const entry of entries) {
        const [name, schema, fn] = entry;
        if (name === inputName) {
            return fn(...args);
        }
    }
}
